import assert from "node:assert/strict";
import * as THREE from "three/webgpu";
import { ArenaWorld } from "../src/world.js";
import { graphicsProfile } from "../src/gameData.js";
import { surfaceTextures } from "../src/surfaceTextures.js";
import { Fighter } from "../src/player.js";

const world = new ArenaWorld(new THREE.Scene(), "FOUNDRY111");
assert.ok(world.scene.fogNode, "height fog separates distant skyline from readable close combat");
assert.equal(world.skylineLights.count, 80);
assert.ok(world.group.getObjectByName("Cyan relay arcologies — layered bodies").material.emissiveNode, "distant buildings have window emission");
const camera = new THREE.PerspectiveCamera();
const colliders = world.obstacles.map(item => [item.x, item.z, item.w, item.h, item.d, item.baseY]);
const occluders = [...world.cameraOccluders];
assert.ok(world.decorativeDetails.length >= 30);
assert.ok(world.decorativeDetails.every(mesh => !occluders.includes(mesh) && !mesh.castShadow));
const detail = world.decorativeDetails.find(mesh => !mesh.isInstancedMesh);
detail.updateWorldMatrix(true, false);
const center = detail.geometry.boundingSphere.center.clone().applyMatrix4(detail.matrixWorld);
const radius = detail.geometry.boundingSphere.radius * detail.matrixWorld.getMaxScaleOnAxis();
for (const level of ["high", "medium", "low", "high"]) {
  const profile = graphicsProfile(level);
  world.setGraphicsProfile(profile);
  camera.position.copy(center);
  world.updatePresentation(camera);
  assert.equal(detail.visible, true, "close detail is restored after quality or camera changes");
  camera.position.x += profile.detailDistance + radius + 4;
  world.updatePresentation(camera);
  assert.equal(detail.visible, true, "hysteresis keeps detail stable near the boundary");
  camera.position.x += 8;
  world.updatePresentation(camera);
  assert.equal(detail.visible, false, "distant decoration is excluded from draw submission");
  camera.position.x -= 8;
  world.updatePresentation(camera);
  assert.equal(detail.visible, false, "hidden details do not chatter at the boundary");
  assert.equal(world.lightShafts.count, level === "low" ? 0 : level === "medium" ? 2 : 4);
  assert.equal(world.waterLightStrength.value, level === "low" ? .35 : level === "medium" ? .7 : 1);
}
assert.equal(world.ground.material.colorNode, world.waterLight);
assert.ok(world.platforms.every(item => item.mesh.material.colorNode === world.waterLight), "raised decks share world-space caustics");
assert.equal(world.ground.material.emissiveIntensity, 0, "caustics receive lighting and shadows instead of emitting bloom");
assert.equal(world.lightShafts.castShadow, false);
world.time = 12;
world.updatePresentation(camera, true); assert.equal(world.atmosphereTime.value, 0);
world.updatePresentation(camera, false); assert.equal(world.atmosphereTime.value, 12);
assert.equal(world.lightShafts.material.depthWrite, false);
assert.deepEqual(world.obstacles.map(item => [item.x, item.z, item.w, item.h, item.d, item.baseY]), colliders);
assert.deepEqual(world.cameraOccluders, occluders);
assert.ok(world.platforms.every(item => item.mesh.visible), "distance quality cannot remove playable decks");
const maps = surfaceTextures("CONCRETE-QA", 28, false, "concrete");
assert.ok(maps[2].image.data.every((value, index) => index % 4 !== 2 || value === 0), "concrete is dielectric");
assert.ok(new Set(maps[0].image.data).size > 16, "aggregate is baked into the shared surface atlas");
maps.forEach(map => map.dispose());
let disposed = 0;
world.lightShafts.material.addEventListener("dispose", () => disposed++);
world.dispose(); assert.equal(disposed, 1);
assert.equal(world.scene.fogNode, world.previousFogNode, "match cleanup restores prior fog");
const hero = new Fighter(new THREE.Scene(), { id: "back-glow", color: 0x227799, accent: 0x55ddff }, ["blaster"], new THREE.Vector3());
const floor = { resolve(p) { p.y = 0; return { grounded: true }; }, boostAt: () => null };
const look = new THREE.Vector3(0, 0, 1);
for (let frame = 0; frame < 60; frame++) hero.update(1 / 60, look, look, {}, floor);
assert.ok(hero.backGlow > .8 && hero.backHaloMaterial.opacity > .35, "movement lights the rear silhouette");
for (let frame = 0; frame < 150; frame++) hero.update(1 / 60, new THREE.Vector3(), look, {}, floor);
assert.ok(hero.backGlow < .01, "stopping smoothly dims the glow");
hero.grounded = false; hero.velocity.y = 12;
hero.update(.1, new THREE.Vector3(), look, {}, { resolve: () => ({ grounded: false }), boostAt: () => null });
assert.ok(hero.backGlow > .4, "vertical movement also lights the back");
hero.alive = false; hero.deathTimer = 1.4; hero.updateDeath(.1);
assert.equal(hero.backHaloMaterial.opacity, 0);
hero.respawn(new THREE.Vector3()); assert.equal(hero.backGlow, 0); assert.equal(hero.backVentMaterial.opacity, .12);
assert.equal(hero.backHaloMaterial.depthWrite, false); assert.equal(hero.backHaloMaterial.depthTest, true);
let backDisposed = 0;
hero.backHaloMaterial.addEventListener("dispose", () => backDisposed++);
hero.backVentMaterial.addEventListener("dispose", () => backDisposed++);
hero.dispose(); assert.equal(backDisposed, 2);
console.log("Arena detail hysteresis, tier transitions, immutable collision, material channels and atmosphere lifecycle passed.");
