import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { WEAPONS } from "../src/gameData.js";
import TEXT, { formatText } from "../src/playerText.js";
import { sanitizeLoadoutSlots } from "../src/multiplayerProtocol.js";

const source = await readFile(new URL("../src/globalMultiplayer.js", import.meta.url), "utf8");
let savedSettings = null, saveCount = 0;
const Controller = new Function("MultiplayerClient", "sanitizeLoadoutSlots", "sanitizePlayerName", "saveSettings", "WEAPONS", "TEXT", "formatText", `${source.replace(/^import .*;\r?\n/gm, "").replace("export class", "class")}\nreturn GlobalMultiplayer;`)(null, sanitizeLoadoutSlots, null, settings => { savedSettings = structuredClone(settings); saveCount++; }, WEAPONS, TEXT, formatText);
const sent = [], status = {};
const game = { mode: "global", state: "lobby", settings: { loadout: ["blaster", "shotgun", "machine_gun", "rocket_launcher", "railgun"] }, multiplayer: { send: (type, payload) => { sent.push({ type, payload }); return true; } } };
const controller = new Controller(game, { querySelector: () => status }, () => "");
const previousDocument = globalThis.document;
try {
  globalThis.document = { activeElement: { closest: () => null, hasAttribute: () => false } };
  game.updateLoadoutUi = (...args) => { game.refreshArguments = args; };
  controller.updateSlots();
  assert.deepEqual(game.refreshArguments, ["", false], "passive waiting-room refreshes preserve the saved-set selector");
} finally {
  if (previousDocument === undefined) delete globalThis.document; else globalThis.document = previousDocument;
}
controller.updateSlots = () => {};
controller.slots = ["rocket_launcher", "shotgun", "railgun", null, null];
assert.equal(controller.handleClick({ dataset: { loadoutRemove: "1" } }), false, "the removed weapon action is unavailable in waiting rooms");
assert.deepEqual(controller.slots, ["rocket_launcher", "shotgun", "railgun", null, null]);
assert.equal(controller.handleClick({ dataset: { weaponChoice: "mine" } }), false, "weapon browsing is handled by the shared preview action");
assert.deepEqual(controller.slots, ["rocket_launcher", "shotgun", "railgun", null, null], "browsing never changes waiting-room weapons");
controller.moveSlot(0, 4);
assert.deepEqual(controller.slots, [null, "shotgun", "railgun", null, "rocket_launcher"]);
assert.equal(sent.at(-1).type, "lobby_loadout");
assert.deepEqual(sent.at(-1).payload.loadout, controller.slots);
const before = [...controller.slots]; controller.moveSlot(1, 8); assert.deepEqual(controller.slots, before);
assert.equal(savedSettings, null, "random waiting-room slots do not replace the last complete loadout");
controller.ui.querySelector = selector => selector === "[data-global-slots]" ? null : status;
controller.updateSlots = Controller.prototype.updateSlots;
controller.slots = ["railgun", "blaster", "shotgun", "mine", "hammer"];
controller.sendSlots();
assert.deepEqual(savedSettings.loadout, controller.slots, "complete waiting-room edits become the last used loadout even without a visible armory");
controller.updateSlots();
assert.equal(saveCount, 1, "passive updates do not repeatedly save an unchanged loadout");
controller.slots = ["railgun", null, "shotgun", "mine", "hammer"];
controller.updateSlots();
assert.deepEqual(game.settings.loadout, savedSettings.loadout, "partial random slots retain the last complete loadout");
assert.equal(saveCount, 1, "partial waiting-room slots are not saved as a local loadout");
game.multiplayer.send = () => false; controller.sendSlots(); assert.equal(status.textContent, TEXT.globalLobby.connectionLost);
controller.directory = { connected: true };
controller.connectionStatus = controller.renderRoom = () => {};
game.settings.loadoutPresets = [{ weaponIds: ["blaster", "shotgun", "machine_gun", "rocket_launcher", "railgun"] }, null, null];
game.settings.defaultLoadoutPreset = 0;
game.connectOnlineMatch = async () => ({ type: "welcome" });
await controller.join("REMEMBERED");
assert.deepEqual(controller.slots, game.settings.loadout, "joining a public room uses the last loadout even if a legacy saved default remains");
assert.equal(TEXT.setup.modes.global.tag, "GLOBAL", "the game HUD must support the public mode, not just its menus");
const main = await readFile(new URL("../src/main.js", import.meta.url), "utf8");
assert.match(main, /const countdown = this.mode === "global" \? null : this.sound.startCountdown/, "public rounds do not add a second audio countdown after their server countdown");
console.log("Global waiting-room slot edits, server updates, offline feedback, HUD mode, and single-countdown checks passed.");
