import assert from "node:assert/strict";
import { setJourney } from "../src/journeys.js";
import { readFileSync } from "node:fs";
import * as data from "../src/gameData.js";
import { clampBotCount } from "../src/botBrain.js";
import TEXT, { formatText } from "../src/playerText.js";

const source = readFileSync(new URL("../src/main.js", import.meta.url), "utf8");
const controller = source.slice(source.indexOf("class BlasterBattle"), source.indexOf("\nconst game = new BlasterBattle")).replaceAll("import.meta.url", JSON.stringify(import.meta.url));
const nodes = new Map();
const categories = data.WEAPON_GROUPS.map(group => {
  const choices = group.ids.map(id => {
    const classes = new Set(), attributes = new Map(), label = {}, image = {}, mutations = [];
    return { dataset: { weaponChoice: id }, classes, attributes, label, image, mutations,
      classList: { toggle: (name, enabled) => { mutations.push(name); return enabled ? classes.add(name) : classes.delete(name); } },
      setAttribute: (name, value) => { mutations.push(name); attributes.set(name, value); }, querySelector: selector => selector === "img" ? image : label };
  }), summary = {};
  return { dataset: { weaponCategory: group.id }, choices, querySelector: () => summary, querySelectorAll: () => choices };
});
const filters = ["all", ...data.WEAPON_GROUPS.map(group => group.id)].map(id => ({ dataset: { weaponFilter: id }, setAttribute() {} }));
const choices = categories.flatMap(group => group.choices);
const saveButtons = [{}];
const ui = { querySelector: selector => nodes.get(selector) || choices.find(choice => selector === `[data-weapon-choice="${choice.dataset.weaponChoice}"]`) || null, querySelectorAll: selector => selector === "[data-weapon-category]" ? categories : selector === "[data-weapon-filter]" ? filters : selector === "[data-weapon-choice]" ? choices : selector === "[data-preset-save]" ? saveButtons : [] };
const bindings = { ...data, TEXT, formatText, ui, setJourney, clampBotCount, resourceURL: path => path, MENU_ACCENTS: { quick: "#ef3f58", private: "#52e9ff", training: "#b86cff" }, menuAtmosphereMarkup: () => "", escapeHtml: value => String(value).replaceAll('"', '&quot;').replaceAll('<', '&lt;'), WEAPON_CATEGORY_BY_ID: Object.fromEntries(data.WEAPON_GROUPS.flatMap(group => group.ids.map(id => [id, group]))) };
const Game = new Function(...Object.keys(bindings), `return ${controller}`)(...Object.values(bindings));
const storage = new Map();
globalThis.localStorage = { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) };
const game = Object.create(Game.prototype);
const preloadSeeds = [];
game.queueArenaPreparation = seed => preloadSeeds.push(seed);
game.queueGameplayPreparation = game.prepareGameplayResources = () => assert.fail("interactive setup and lobby changes must not start gameplay GPU preparation");
game.settings = data.loadSettings();
assert.deepEqual(game.settings.loadout, data.RECOMMENDED_LOADOUT, "new players arrive with the complete recommended kit");
game.mode = "training";
game.state = "menu";
game.players = [];
game.settings.loadout = ["railgun", "blaster", "shotgun", "mine", "needle_launcher"];
game.settings.loadoutPresets = [{ weaponIds: [...game.settings.loadout] }, null, null];
game.announceLoadout = value => { game.announcement = value; };
game.pulseMenuEnergy = () => {};
game.menuAccent = () => "#52e9ff";
game.sound = { resume() {}, setVolume() {}, startMusic() {}, play() {}, accentMenuAction() {} };
nodes.set("[data-weapon-search]", { value: "", focus() {} });
nodes.set("[data-weapon-empty]", {});
nodes.set('[data-loadout-edit="0"]', { focus() { game.focusedSlot = 0; } });

const markup = game.loadoutEditorMarkup();
assert.match(markup, /data-weapon-picker/, "the armory includes the weapon library");
assert.doesNotMatch(markup, /data-weapon-picker hidden/, "the weapon library is always visible");
assert.match(markup, /data-loadout-equip/, "weapon previews have an explicit equip action");
assert.match(markup, /data-loadout-recommended/, "a beginner kit is available without managing presets");
assert.doesNotMatch(markup, /preset-manager|data-loadout-presets|data-preset-name|data-preset-default|data-preset-clear/, "the old saved-set manager and naming/default controls are removed");
assert.doesNotMatch(markup, /data-loadout-remove/, "equipped slots have no remove action");
assert.match(markup, /data-preset-save/, "Save set is available alongside the equipped slots");
assert.match(markup, /<h3>Equipped weapons<\/h3>[\s\S]*?data-action="loadout-help"/, "the question-circle help action sits beside Equipped weapons");
const showModal = game.showModal;
game.showModal = (html, options) => { game.helpModal = { html, options }; };
game.showLoadoutHelp();
assert.ok(game.helpModal.html.includes(TEXT.setup.loadout.detailedHelp), "the modal contains the complete controls help");
assert.match(game.helpModal.html, /data-action="close-loadout-help"[^>]*>OK<\/button>/, "OK closes the controls help modal");
assert.deepEqual(game.helpModal.options, { kind: "loadout-help", cancel: "close" }, "the native help dialog also supports dismissal");
game.showModal = showModal;
assert.equal((markup.match(/data-loadout-edit=/g) || []).length, 5);
assert.equal(game.activeLoadoutSlot, 0, "the first slot is ready to edit on arrival");
assert.equal(game.previewWeaponId, "railgun", "the first equipped weapon is previewed on arrival");
assert.match(markup, /data-weapon-preview="railgun:0:0"/, "the initial preview records its weapon and slot state on its DOM node");
const libraryMarkup = game.weaponCategoriesMarkup();
const libraryImages = [...libraryMarkup.matchAll(/<img\b[^>]*>/g)].map(([tag]) => tag);
const libraryCards = new Map([...libraryMarkup.matchAll(/<button\b[^>]*data-weapon-choice="([^"]+)"[^>]*>[\s\S]*?<\/button>/g)].map(([card, id]) => [id, card]));
assert.equal(libraryImages.length, Object.keys(data.WEAPONS).length, "every weapon card has one rendered game-model image");
for (const id of Object.keys(data.WEAPONS)) {
  const image = libraryImages.find(tag => tag.includes(`src="/weapons/${id}.webp"`));
  assert.ok(image, `${id} uses its own rendered game-model asset`);
  assert.match(image, /class="weapon-render"/);
  assert.match(image, /loading="lazy"/, "library images defer loading until needed");
  assert.match(image, /width="512" height="320"/, "image dimensions reserve stable layout space");
  assert.match(image, /alt=""/, "adjacent weapon names provide the accessible label");
  game.previewWeaponId = id;
  const preview = game.weaponPreviewMarkup();
  assert.ok(preview.includes(`src="/weapons/${id}.webp"`), "the large preview uses the same weapon render as its card");
  assert.doesNotMatch(preview, /loading="lazy"/, "the current large preview loads immediately");
  const weapon = data.WEAPONS[id], card = libraryCards.get(id);
  const stats = card.match(/<div class="weapon-stats">[\s\S]*?<\/div>/)?.[0];
  assert.ok(stats && preview.includes(stats), `${id} shares the same permanent stats in its card and preview`);
  assert.doesNotMatch(stats, /\bhidden\b/, "weapon stats are visible without opening a disclosure");
  for (const html of [card, preview]) {
    assert.ok(html.includes(weapon.description), `${id} restores its original description beside the stats`);
    assert.doesNotMatch(html, /<(?:details|summary)\b/, "weapon information has no disclosure controls");
  }
  assert.ok(stats.includes(`<strong>${weapon.damage}</strong>`), `${id} preserves its unrounded base damage`);
  if (data.weaponUsesAmmo(weapon)) {
    assert.ok(stats.includes(`<span class="stat-label">${TEXT.setup.loadout.magazineLabel}</span><strong>${weapon.ammo}</strong>`));
    assert.ok(stats.includes(`<span class="stat-label">${TEXT.setup.loadout.reloadLabel}</span><strong>${formatText(TEXT.setup.loadout.reloadSeconds, { seconds: weapon.reload.toFixed(1) })}</strong>`));
  } else {
    assert.ok(stats.includes(TEXT.setup.loadout.noReload), `${id} attacks without ammunition or reloading`);
    for (const label of [TEXT.setup.loadout.magazineLabel, TEXT.setup.loadout.reloadLabel]) assert.ok(!stats.includes(`<span class="stat-label">${label}</span>`), "ammo-free weapons omit magazine and reload values");
  }
}
for (const [id, label, damage] of [["shotgun", TEXT.setup.loadout.pelletDamageLabel, 8], ["charged_energy_rifle", TEXT.setup.loadout.maxDamageLabel, 76], ["gravity_beam", TEXT.setup.loadout.damageLabel, 3.5]]) {
  assert.ok(libraryCards.get(id).includes(`<span class="stat-label">${label}</span><strong>${damage}</strong>`), `${id} labels per-pellet, maximum or fractional damage accurately`);
}
game.previewWeaponId = "railgun";
const watchedRegions = new Map();
for (const selector of ["[data-preset-select]", "[data-loadout-order]", "[data-loadout-actions]", "[data-weapon-preview]"]) {
  const region = { dataset: {}, writes: 0, firstChild: {}, html: "", get innerHTML() { return this.html; }, set innerHTML(value) { this.html = value; this.writes++; this.firstChild = {}; } };
  nodes.set(selector, region); watchedRegions.set(selector, region);
}
game.updateLoadoutUi();
for (const region of watchedRegions.values()) region.writes = 0;
for (const choice of choices) choice.mutations.length = 0;
const retainedChildren = new Map([...watchedRegions].map(([selector, region]) => [selector, region.firstChild]));
const retainedImages = choices.map(choice => choice.querySelector("img"));

const click = dataset => ui.onclick({ target: { closest: () => ({ dataset, hasAttribute: name => name === "data-loadout-equip" && "loadoutEquip" in dataset || name === "data-loadout-recommended" && "loadoutRecommended" in dataset || name === "data-preset-save" && "presetSave" in dataset, setAttribute() {}, classList: { toggle() {} }, querySelector: () => ({}) }) } });
game.bindUi();
const beforePreview = [...game.settings.loadout], beforePreviewStorage = [...storage];
click({ weaponChoice: "rocket_launcher" });
assert.equal(game.previewWeaponId, "rocket_launcher");
assert.deepEqual(game.settings.loadout, beforePreview, "browsing previews never silently replaces a weapon");
assert.deepEqual([...storage], beforePreviewStorage, "previewing does not save an unintended loadout");
const previewed = choices.find(button => button.dataset.weaponChoice === "rocket_launcher");
const equipped = choices.find(button => button.dataset.weaponChoice === "railgun");
assert.equal(previewed.attributes.get("aria-pressed"), "true", "pressed state identifies the current preview");
assert.equal(previewed.label.hidden, true, "an unequipped preview is not labeled equipped");
assert.equal(equipped.attributes.get("aria-pressed"), "false", "equipped weapons do not masquerade as the selected preview");
assert.equal(equipped.label.hidden, false, "equipped labels remain visible while browsing other weapons");
assert.deepEqual(choices.filter(choice => choice.mutations.length).map(choice => choice.dataset.weaponChoice).sort(), ["railgun", "rocket_launcher"], "browsing touches only the old and new preview cards");
for (const [selector, region] of watchedRegions) {
  if (selector === "[data-weapon-preview]") continue;
  assert.equal(region.writes, 0, "browsing does not rebuild equipped slots, actions or preset controls");
  assert.equal(region.firstChild, retainedChildren.get(selector), "unrelated control nodes keep their identity");
}
for (let index = 0; index < choices.length; index++) assert.equal(choices[index].querySelector("img"), retainedImages[index], "browsing keeps every card image node");
const hero = watchedRegions.get("[data-weapon-preview]"), heroImage = hero.firstChild;
assert.equal(hero.writes, 1, "a changed weapon updates the large preview once");
for (const choice of choices) choice.mutations.length = 0;
click({ weaponChoice: "rocket_launcher" });
assert.equal(hero.writes, 1, "clicking the same weapon does not rebuild its static preview");
assert.equal(hero.firstChild, heroImage, "repeated previews retain the hero image and visible weapon information");
assert.ok(choices.every(choice => choice.mutations.length === 0), "clicking the same preview performs no card writes");
game.updateLoadoutUi("", false);
assert.equal(hero.writes, 1, "unchanged full or lobby refreshes keep the current preview");
assert.equal(hero.firstChild, heroImage, "unchanged room updates retain the hero image and weapon information nodes");
nodes.get("[data-weapon-search]").value = "long range";
game.filterWeaponPicker();
assert.equal(equipped.hidden, false, "search finds weapons by their plain-language role");
assert.equal(game.activeLoadoutSlot, 0, "search keeps the selected slot");
click({ weaponFilter: data.WEAPON_GROUPS[1].id });
assert.equal(nodes.get("[data-weapon-search]").value, "", "choosing a category clears the previous search");
assert.equal(game.activeLoadoutSlot, 0, "category changes keep the selected slot");
assert.equal(game.previewWeaponId, "rocket_launcher", "category changes preserve the preview until another weapon is chosen");
assert.deepEqual(game.settings.loadout, beforePreview, "search and filters do not commit the preview");
assert.equal(hero.firstChild, heroImage, "search and category changes retain the static hero image");
click({ loadoutEquip: "" });
assert.equal(game.settings.loadout[0], "rocket_launcher", "the equip action commits the previewed weapon");
assert.equal(previewed.label.hidden, false, "equipping updates the weapon's equipped label");
assert.equal(equipped.label.hidden, true, "replacing a weapon clears its equipped label");
assert.equal(game.activeLoadoutSlot, 0, "equipping leaves the active slot selected");
assert.equal(game.focusedSlot, 0, "equipping restores keyboard focus to the enabled slot button");
assert.deepEqual(data.loadSettings().loadout, game.settings.loadout, "equipping persists the loadout");
assert.equal(hero.writes, 2, "equipping updates the preview action when its equipped slot changes");
const equippedHero = hero.firstChild;
game.updateLoadoutUi("", false);
assert.equal(hero.firstChild, equippedHero, "a repeated equip acknowledgement keeps the refreshed preview node");
game.editLoadoutSlot(1);
assert.equal(hero.writes, 3, "choosing another slot refreshes its weapon preview");
game.previewLoadoutWeapon("rocket_launcher");
const otherSlotHero = hero.firstChild;
game.activeLoadoutSlot = 2;
game.updateLoadoutUi("", false);
assert.notEqual(hero.firstChild, otherSlotHero, "changing the destination slot updates the preview even when its weapon is unchanged");
for (const selector of watchedRegions.keys()) nodes.delete(selector);
game.settings.loadout = [...beforePreview];

game.activeLoadoutSlot = 0;
game.equipLoadoutSlot("blaster");
assert.deepEqual(game.settings.loadout, ["blaster", "railgun", "shotgun", "mine", "needle_launcher"], "equipped weapons swap without duplicates");
game.activeLoadoutSlot = 3;
game.equipLoadoutSlot("hammer");
assert.equal(game.settings.loadout[3], "hammer", "full loadout can replace a slot directly");
game.settings.loadout = game.settings.loadout.slice(0, 4);
game.activeLoadoutSlot = 4;
game.equipLoadoutSlot("mine");
assert.equal(game.settings.loadout.length, 5, "legacy incomplete loadouts can be filled again");
game.settings.loadout = game.settings.loadout.slice(0, 4);
game.equipLoadoutSlot(game.settings.loadout[0]);
assert.equal(game.settings.loadout.length, 4, "moving an already equipped weapon to the empty tail preserves the incomplete loadout");
assert.equal(game.activeLoadoutSlot, 3, "the selected slot follows the weapon after local empty-slot compaction");
assert.equal(game.settings.loadout[game.activeLoadoutSlot], game.previewWeaponId, "the active slot and preview refer to the same weapon after compaction");
game.activeLoadoutSlot = 4;
game.equipLoadoutSlot("mine");
game.activeLoadoutSlot = 2;
game.moveLoadout(2, -1);
assert.equal(game.activeLoadoutSlot, 1, "active controls follow reordering");
game.loadPreset(0);
assert.deepEqual(game.settings.loadout, game.settings.loadoutPresets[0].weaponIds);
assert.match(game.presetOptionsMarkup(), /value="0" selected/);
assert.deepEqual(data.loadSettings().loadoutPresets[0].weaponIds, beforePreview, "saved sets retain their exact order after editing");

const custom = [...game.settings.loadout];
game.renderSetup("quick");
game.renderSetup("quick");
assert.deepEqual(game.settings.loadout, custom, "returning to Quick Play keeps the current custom loadout");
assert.match(ui.innerHTML, /<header>[\s\S]*?data-action="start"[\s\S]*?data-launch-summary[\s\S]*?<\/header>/, "Start sits in the setup header above its match summary");
assert.equal((ui.innerHTML.match(/data-action="start"/g) || []).length, 1, "the old bottom Start section is removed");
for (const mode of ["training", "private", "quick"]) {
  game.renderSetup(mode);
  assert.equal(game.mode, mode);
  assert.equal(preloadSeeds.at(-1), game.seed, "Armory entry queues optional CPU work for the selected seed");
  assert.deepEqual(game.settings.loadout, custom, "changing setup mode preserves a custom kit while queuing optional CPU preparation");
}
game.settings.defaultLoadoutPreset = 0;
game.settings.loadout = [...data.DEFAULT_LOADOUT];
game.renderSetup("quick");
assert.deepEqual(game.settings.loadout, data.DEFAULT_LOADOUT, "a legacy saved-default field cannot replace the last used loadout on entry");
delete game.settings.defaultLoadoutPreset;
click({ loadoutRecommended: "" });
assert.deepEqual(game.settings.loadout, data.RECOMMENDED_LOADOUT, "the recommended action equips a complete beginner kit");
assert.deepEqual(data.loadSettings().loadout, data.RECOMMENDED_LOADOUT, "the recommended kit persists locally");
const presetSelect = { innerHTML: "Current selection" };
nodes.set("[data-preset-select]", presetSelect);
game.settings.loadout = [...game.settings.loadoutPresets[0].weaponIds];
game.updateLoadoutUi("", false);
assert.equal(presetSelect.innerHTML, "Current selection", "passive updates preserve the preset dropdown");
assert.equal(presetSelect.value, "0", "passive updates select the matching preset without replacing its options");
assert.ok(saveButtons.every(button => button.disabled === false), "passive updates enable Save set for a complete kit");
game.settings.loadout = game.settings.loadout.slice(0, 4);
game.updateLoadoutUi("", false);
assert.equal(presetSelect.value, "0", "editing a kit retains the selected saved-set destination");
assert.ok(saveButtons.every(button => button.disabled === true), "passive updates disable Save set for incomplete kits");
game.settings.loadout = [...game.settings.loadoutPresets[0].weaponIds];
game.updateLoadoutUi("", false);
assert.equal(presetSelect.value, "0", "restoring the preset kit selects it again without replacing options");
game.settings.loadout = [...data.RECOMMENDED_LOADOUT];
game.loadPreset(1);
assert.equal(game.activeLoadoutPreset, 1, "choosing an empty numbered set selects it as the save destination");
assert.deepEqual(game.settings.loadout, data.RECOMMENDED_LOADOUT, "choosing an empty set keeps the current weapons");
click({ presetSave: "" });
assert.equal(game.settings.loadoutPresets.length, 3, "the three numbered saved-set destinations stay fixed");
assert.deepEqual(game.settings.loadoutPresets[1], { weaponIds: [...data.RECOMMENDED_LOADOUT] }, "saved sets contain ordered weapons without editable names");
assert.deepEqual(data.loadSettings().loadoutPresets[1], game.settings.loadoutPresets[1], "Save set persists the numbered set");
assert.deepEqual(game.settings.loadoutPresets[0].weaponIds, beforePreview, "saving the selected set preserves other favorites");
assert.ok(presetSelect.innerHTML.includes(formatText(TEXT.defaults.presetName, { number: 2 })), "the dropdown labels saved sets by number");
assert.ok(presetSelect.innerHTML.includes(formatText(TEXT.defaults.presetName, { number: 3 })), "an empty destination remains available in the dropdown");
assert.doesNotMatch(presetSelect.innerHTML, /value=""/, "saved-set selection has no Custom placeholder");
game.settings.loadout = ["railgun", "blaster", "shotgun", "mine", "hammer"];
game.updateLoadoutUi("", false);
assert.equal(presetSelect.value, "1", "weapon edits retain the chosen replacement destination");
click({ presetSave: "" });
assert.deepEqual(game.settings.loadoutPresets[1].weaponIds, game.settings.loadout, "Save set replaces the selected favorite with the current weapons");
assert.deepEqual(data.loadSettings().loadoutPresets[1].weaponIds, game.settings.loadout, "replacement persists without a separate confirmation");
assert.deepEqual(data.loadSettings().loadout, game.settings.loadout, "reloading settings restores the last saved current loadout");
const savedReplacement = [...game.settings.loadoutPresets[1].weaponIds];
game.settings.loadout = game.settings.loadout.slice(0, 4);
game.savePreset();
assert.deepEqual(game.settings.loadoutPresets[1].weaponIds, savedReplacement, "an incomplete kit cannot replace a saved set");
for (const rejected of [["blaster", "blaster", "shotgun", "mine", "hammer"], ["missing", "blaster", "shotgun", "mine", "hammer"], ["toString", "blaster", "shotgun", "mine", "hammer"]]) {
  game.settings.loadout = rejected;
  game.savePreset();
  assert.deepEqual(game.settings.loadoutPresets[1].weaponIds, savedReplacement, "duplicate or unknown weapons cannot replace a saved set");
}
game.settings.loadout = [...data.RECOMMENDED_LOADOUT];
nodes.delete("[data-preset-select]");
game.mode = "training";

game.botDifficulty = "veteran";
game.timeLimitMinutes = 5;
game.settings.botCount = 12;
game.settings.matchSettings.training.botsStandStill = true;
assert.ok(game.matchSummary().includes(formatText(TEXT.setup.matchSummary, { bots: 12, difficulty: TEXT.setup.difficulties.veteran, minutes: 5 })));
assert.ok(game.matchSummary().includes(`${TEXT.trainingControls.botsStandStill}: ${TEXT.trainingControls.on}`));
const settingsSummary = {}, launchSummary = {};
nodes.set("[data-match-summary]", settingsSummary);
nodes.set("[data-launch-summary]", launchSummary);
for (const [selector, value] of [["#display-name", "Tester"], ["#map-seed", "TEST"], ["#bot-difficulty", "rookie"], ["#bot-count", "4"], ["#time-limit", "7"]]) nodes.set(selector, { value });
game.captureSetupPreferences();
assert.equal(preloadSeeds.at(-1), "TEST", "committed setup preferences retarget optional CPU preparation");
assert.equal(settingsSummary.textContent, game.matchSummary());
assert.equal(launchSummary.textContent, game.matchSummary(), "match preferences update the summary beside Start");
const beforeTrainingToggle = launchSummary.textContent;
click({ trainingToggle: "botsStandStill" });
assert.notEqual(launchSummary.textContent, beforeTrainingToggle);
assert.equal(launchSummary.textContent, settingsSummary.textContent, "training toggles keep both match summaries synchronized");

let sent = 0;
game.mode = "global";
game.state = "lobby";
game.globalMultiplayer = { slots: ["railgun", null, "blaster", null, null], sendSlots: () => { sent++; } };
game.activeLoadoutSlot = 1;
game.previewLoadoutWeapon("railgun");
assert.equal(sent, 0, "previewing in a waiting room sends no lobby changes");
assert.deepEqual(game.globalMultiplayer.slots, ["railgun", null, "blaster", null, null]);
game.equipLoadoutSlot("railgun");
assert.deepEqual(game.globalMultiplayer.slots, [null, "railgun", "blaster", null, null], "global swaps preserve random slots");
assert.equal(sent, 1);
game.loadPreset(0);
assert.deepEqual(game.globalMultiplayer.slots, game.settings.loadoutPresets[0].weaponIds, "presets apply to global waiting rooms");
assert.equal(sent, 2);
game.settings.loadout = ["hammer"];
game.savePreset();
assert.deepEqual(game.settings.loadoutPresets[0].weaponIds, game.globalMultiplayer.slots, "saving the chosen room set retains its slot");
game.globalMultiplayer.slots = ["railgun", "blaster", "shotgun", "mine", "hammer"];
game.loadPreset(2);
assert.deepEqual(game.globalMultiplayer.slots, ["railgun", "blaster", "shotgun", "mine", "hammer"], "choosing an empty room set preserves the waiting-room kit");
game.savePreset();
assert.deepEqual(game.settings.loadoutPresets[2].weaponIds, game.globalMultiplayer.slots, "global set saves replace the selected destination using the actual room loadout");
assert.match(game.loadoutEditorMarkup(true), /data-global-slots/);
game.applyRecommendedLoadout();
assert.deepEqual(game.globalMultiplayer.slots, data.RECOMMENDED_LOADOUT, "the recommended kit applies to the actual waiting-room slots");
assert.equal(sent, 3, "equipping the recommended kit sends one waiting-room update");
console.log("Armory previews, explicit equip, replacement/swaps, reorder, recommended kit, numbered saved sets, last-used loadout, controls help, training summary and global random slots passed.");

// Render multiplayer setup with a local service stub; no live room is created.
const globalSource = readFileSync(new URL("../src/globalMultiplayer.js", import.meta.url), "utf8").replace(/^import .*;\r?\n/gm, "").replace("export class", "class");
const Global = new Function("TEXT", "formatText", "WEAPONS", `${globalSource}\nreturn GlobalMultiplayer;`)(TEXT, formatText, data.WEAPONS);
const roomNodes = new Map();
const roomUi = { innerHTML: "", querySelector: selector => {
  if (selector === "[data-global-waiting]") return null;
  if (!roomNodes.has(selector)) roomNodes.set(selector, {});
  return roomNodes.get(selector);
}, querySelectorAll: () => [] };
const room = new Global(game, roomUi, () => "");
game.globalMultiplayer = room;
game.bindUi = () => {};
game.setMatchLoading = () => {};
game.sound = { setPaused() {}, setMusicScene() {}, startMusic() {} };
game.multiplayer = { playerId: "local", connected: true };
room.renderCreate();
assert.match(roomUi.innerHTML, /id="global-name"[\s\S]*?<details class="setup-options">[\s\S]*?id="global-bots"/, "global room identity stays visible while advanced settings collapse");
room.updateSlots = () => {};
room.renderRoom({ type: "welcome", roomName: "Test room", hostId: "local", phase: "lobby", humanCapacity: 4, configuredBotCount: 2, difficulty: "normal", timeLimitMinutes: 3, players: [{ id: "local", name: "Tester", pendingLoadout: ["railgun", null, null, null, null] }] });
assert.match(roomUi.innerHTML, new RegExp(TEXT.globalLobby.weapons));
assert.doesNotMatch(roomUi.innerHTML, /data-weapon-picker hidden/);
assert.match(roomUi.innerHTML, new RegExp(TEXT.globalLobby.emptySlot));
assert.equal(game.activeLoadoutSlot, 0, "waiting rooms open with the first armory slot selected");
assert.match(roomUi.innerHTML, /data-preset-select/);
assert.equal(roomNodes.get("[data-global-rules]").textContent, formatText(TEXT.setup.matchSummary, { bots: 2, difficulty: TEXT.setup.difficulties.normal, minutes: 3 }));
room.renderRoom({ type: "lobby", configuredBotCount: 3 });
assert.equal(roomNodes.get("[data-global-rules]").textContent, formatText(TEXT.setup.matchSummary, { bots: 3, difficulty: TEXT.setup.difficulties.normal, minutes: 3 }), "passive room updates refresh rules without gameplay preparation");
assert.equal(preloadSeeds.at(-1), game.seed, "a waiting room queues optional CPU work for its known seed");
game.clearMatch = () => {};
game.multiplayer.send = () => {};
room.directory = { connected: true };
const beforeDirectory = preloadSeeds.length;
await room.open();
assert.equal(game.state, "global", "opening a connected public directory stays in the menu");
assert.equal(preloadSeeds.length, beforeDirectory, "the public directory does not speculate on an unknown room seed");
game.mode = "private";
game.renderPrivateLobby({ phase: "lobby", roomCode: "WAITING", hostId: "local", configuredBotCount: 2, difficulty: "normal", timeLimitMinutes: 3, players: [{ id: "local", name: "Tester" }] });
assert.equal(game.state, "lobby");
assert.equal(game.seed, "WAITING", "private waiting rooms update their seed without building the arena");
assert.equal(preloadSeeds.at(-1), "WAITING", "private waiting rooms retarget optional CPU preparation");
console.log("Setup and private/public waiting-room updates queue optional CPU preparation while staying free of gameplay GPU warmup; armory settings and slots remain available.");
