import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import * as data from "../src/gameData.js";
import TEXT, { formatText } from "../src/playerText.js";

const source = readFileSync(new URL("../src/main.js", import.meta.url), "utf8");
const controller = source.slice(source.indexOf("class BlasterBattle"), source.indexOf("\nconst game = new BlasterBattle")).replaceAll("import.meta.url", JSON.stringify(import.meta.url));
const nodes = new Map();
const ui = { querySelector: selector => nodes.get(selector) || null, querySelectorAll: () => [] };
const bindings = { ...data, TEXT, formatText, ui, escapeHtml: value => String(value).replaceAll('"', '&quot;').replaceAll('<', '&lt;'), WEAPON_CATEGORY_BY_ID: Object.fromEntries(data.WEAPON_GROUPS.flatMap(group => group.ids.map(id => [id, group]))), WEAPON_INDEX_BY_ID: {}, weaponPreviewVariables: () => "" };
const Game = new Function(...Object.keys(bindings), `return ${controller}`)(...Object.values(bindings));
const storage = new Map();
globalThis.localStorage = { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) };
const game = Object.create(Game.prototype);
game.settings = data.loadSettings();
game.mode = "training";
game.state = "menu";
game.settings.loadout = ["railgun", "blaster", "shotgun", "mine", "needle_launcher"];
game.settings.loadoutPresets = [{ name: 'Favorite <set>', weaponIds: [...game.settings.loadout] }, null, null];
game.settings.defaultLoadoutPreset = 0;
game.updateLoadoutUi = () => {};
game.closeWeaponPicker = () => { game.activeLoadoutSlot = null; };
game.announceLoadout = value => { game.announcement = value; };

const markup = game.loadoutEditorMarkup();
assert.match(markup, /data-weapon-picker hidden/, "catalogue starts closed");
assert.match(markup, /<details class="preset-manager">/, "preset management starts collapsed");
assert.match(markup, /<details class="loadout-instructions">/, "detailed help starts collapsed");
assert.match(markup, /Favorite &lt;set>/, "preset labels are escaped");
assert.equal((markup.match(/data-loadout-edit=/g) || []).length, 5);
assert.equal((game.loadoutOrderMarkup().match(/class="slot-actions" hidden/g) || []).length, 5);

game.activeLoadoutSlot = 0;
game.equipLoadoutSlot("blaster");
assert.deepEqual(game.settings.loadout, ["blaster", "railgun", "shotgun", "mine", "needle_launcher"], "equipped weapons swap without duplicates");
game.activeLoadoutSlot = 3;
game.equipLoadoutSlot("hammer");
assert.equal(game.settings.loadout[3], "hammer", "full loadout can replace a slot directly");
game.removeLoadout(1);
assert.equal(game.settings.loadout.length, 4);
assert.equal(game.activeLoadoutSlot, 4, "removal targets the newly empty slot");
game.activeLoadoutSlot = 4;
game.equipLoadoutSlot("mine");
assert.equal(game.settings.loadout.length, 5, "removed slots can be filled again");
game.activeLoadoutSlot = 2;
game.moveLoadout(2, -1);
assert.equal(game.activeLoadoutSlot, 1, "active controls follow reordering");
game.loadPreset(0);
assert.deepEqual(game.settings.loadout, game.settings.loadoutPresets[0].weaponIds);
assert.match(game.presetOptionsMarkup(), /value="0" selected/);

game.botDifficulty = "veteran";
game.timeLimitMinutes = 5;
game.settings.botCount = 12;
game.settings.matchSettings.training.botsStandStill = true;
assert.match(game.matchSummary(), /12 bots · veteran · 5 min/);
assert.ok(game.matchSummary().includes(`${TEXT.trainingControls.botsStandStill}: ${TEXT.trainingControls.on}`));

let sent = 0;
game.mode = "global";
game.state = "lobby";
game.globalMultiplayer = { slots: ["railgun", null, "blaster", null, null], sendSlots: () => { sent++; } };
game.activeLoadoutSlot = 1;
game.equipLoadoutSlot("railgun");
assert.deepEqual(game.globalMultiplayer.slots, [null, "railgun", "blaster", null, null], "global swaps preserve random slots");
assert.equal(sent, 1);
game.loadPreset(0);
assert.deepEqual(game.globalMultiplayer.slots, game.settings.loadoutPresets[0].weaponIds, "presets apply to global waiting rooms");
assert.equal(sent, 2);
game.settings.loadout = ["hammer"];
game.savePreset(1);
assert.deepEqual(game.settings.loadoutPresets[1].weaponIds, game.globalMultiplayer.slots, "global preset saves use the actual room loadout");
assert.match(game.loadoutEditorMarkup(true), /data-global-slots/);
console.log("Compact setup checks passed: collapsed panels, replacement, swaps, removal, reorder, presets, training summary, global random slots and persistence.");

// Render multiplayer setup with a local service stub; no live room is created.
const globalSource = readFileSync(new URL("../src/globalMultiplayer.js", import.meta.url), "utf8").replace(/^import .*;\r?\n/gm, "").replace("export class", "class");
const Global = new Function("TEXT", "formatText", "WEAPONS", `${globalSource}\nreturn GlobalMultiplayer;`)(TEXT, formatText, data.WEAPONS);
const roomNodes = new Map();
const roomUi = { innerHTML: "", querySelector: selector => {
  if (selector === "[data-global-waiting]") return null;
  if (!roomNodes.has(selector)) roomNodes.set(selector, {});
  return roomNodes.get(selector);
}, querySelectorAll: () => [] };
const room = new Global(game, roomUi, () => "");
game.globalMultiplayer = room;
game.bindUi = () => {};
game.setMatchLoading = () => {};
game.sound = { setPaused() {}, setMusicScene() {}, startMusic() {} };
game.multiplayer = { playerId: "local", connected: true };
room.renderCreate();
assert.match(roomUi.innerHTML, /id="global-name"[\s\S]*?<details class="setup-options">[\s\S]*?id="global-bots"/, "global room identity stays visible while advanced settings collapse");
room.updateSlots = () => {};
room.renderRoom({ type: "welcome", roomName: "Test room", hostId: "local", phase: "lobby", humanCapacity: 4, configuredBotCount: 2, difficulty: "normal", timeLimitMinutes: 3, players: [{ id: "local", name: "Tester", pendingLoadout: ["railgun", null, null, null, null] }] });
assert.match(roomUi.innerHTML, /Your weapons/);
assert.match(roomUi.innerHTML, /data-weapon-picker hidden/);
assert.match(roomUi.innerHTML, /Random at zero/);
assert.match(roomUi.innerHTML, /data-preset-select/);
assert.equal(roomNodes.get("[data-global-rules]").textContent, "2 bots · normal · 3 min");
console.log("Global creation and waiting-room rendering preserve collapsed settings, shared picker, presets and optional random slots.");
