import assert from "node:assert/strict";
import { setJourney } from "../src/journeys.js";
import { readFileSync } from "node:fs";
import * as data from "../src/gameData.js";
import { clampBotCount } from "../src/botBrain.js";
import TEXT, { formatText } from "../src/playerText.js";

const source = readFileSync(new URL("../src/main.js", import.meta.url), "utf8");
const controller = source.slice(source.indexOf("class BlasterBattle"), source.indexOf("\nconst game = new BlasterBattle")).replaceAll("import.meta.url", JSON.stringify(import.meta.url));
const nodes = new Map();
const categories = data.WEAPON_GROUPS.map(group => {
  const choices = group.ids.map(id => {
    const classes = new Set(), attributes = new Map(), label = {};
    return { dataset: { weaponChoice: id }, classes, attributes, label,
      classList: { toggle: (name, enabled) => enabled ? classes.add(name) : classes.delete(name) },
      setAttribute: (name, value) => attributes.set(name, value), querySelector: () => label };
  }), summary = {};
  return { dataset: { weaponCategory: group.id }, choices, querySelector: () => summary, querySelectorAll: () => choices };
});
const filters = ["all", ...data.WEAPON_GROUPS.map(group => group.id)].map(id => ({ dataset: { weaponFilter: id }, setAttribute() {} }));
const choices = categories.flatMap(group => group.choices);
const saveButtons = Array.from({ length: 3 }, () => ({}));
const ui = { querySelector: selector => nodes.get(selector) || null, querySelectorAll: selector => selector === "[data-weapon-category]" ? categories : selector === "[data-weapon-filter]" ? filters : selector === "[data-weapon-choice]" ? choices : selector === "[data-preset-save]" ? saveButtons : [] };
const bindings = { ...data, TEXT, formatText, ui, setJourney, clampBotCount, MENU_ACCENTS: { quick: "#ef3f58", private: "#52e9ff", training: "#b86cff" }, menuAtmosphereMarkup: () => "", escapeHtml: value => String(value).replaceAll('"', '&quot;').replaceAll('<', '&lt;'), WEAPON_CATEGORY_BY_ID: Object.fromEntries(data.WEAPON_GROUPS.flatMap(group => group.ids.map(id => [id, group]))), WEAPON_INDEX_BY_ID: {}, weaponPreviewVariables: () => "" };
const Game = new Function(...Object.keys(bindings), `return ${controller}`)(...Object.values(bindings));
const storage = new Map();
globalThis.localStorage = { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) };
const game = Object.create(Game.prototype);
game.queueGameplayPreparation = () => {};
game.settings = data.loadSettings();
assert.deepEqual(game.settings.loadout, data.RECOMMENDED_LOADOUT, "new players arrive with the complete recommended kit");
game.mode = "training";
game.state = "menu";
game.players = [];
game.settings.loadout = ["railgun", "blaster", "shotgun", "mine", "needle_launcher"];
game.settings.loadoutPresets = [{ name: 'Favorite <set>', weaponIds: [...game.settings.loadout] }, null, null];
game.settings.defaultLoadoutPreset = 0;
game.announceLoadout = value => { game.announcement = value; };
game.pulseMenuEnergy = () => {};
game.menuAccent = () => "#52e9ff";
game.sound = { resume() {}, setVolume() {}, startMusic() {}, play() {}, accentMenuAction() {} };
nodes.set("[data-weapon-search]", { value: "", focus() {} });
nodes.set("[data-weapon-empty]", {});
nodes.set('[data-loadout-edit="0"]', { focus() { game.focusedSlot = 0; } });

const markup = game.loadoutEditorMarkup();
assert.match(markup, /data-weapon-picker/, "the armory includes the weapon library");
assert.doesNotMatch(markup, /data-weapon-picker hidden/, "the weapon library is always visible");
assert.match(markup, /data-loadout-equip/, "weapon previews have an explicit equip action");
assert.match(markup, /data-loadout-recommended/, "a beginner kit is available without managing presets");
assert.match(markup, /<details class="preset-manager">/, "preset management starts collapsed");
assert.match(markup, /Favorite &lt;set>/, "preset labels are escaped");
assert.equal((markup.match(/data-loadout-edit=/g) || []).length, 5);
assert.equal(game.activeLoadoutSlot, 0, "the first slot is ready to edit on arrival");
assert.equal(game.previewWeaponId, "railgun", "the first equipped weapon is previewed on arrival");

const click = dataset => ui.onclick({ target: { closest: () => ({ dataset, hasAttribute: name => name === "data-loadout-equip" && "loadoutEquip" in dataset || name === "data-loadout-recommended" && "loadoutRecommended" in dataset, setAttribute() {}, classList: { toggle() {} }, querySelector: () => ({}) }) } });
game.bindUi();
const beforePreview = [...game.settings.loadout], beforePreviewStorage = [...storage];
click({ weaponChoice: "rocket_launcher" });
assert.equal(game.previewWeaponId, "rocket_launcher");
assert.deepEqual(game.settings.loadout, beforePreview, "browsing previews never silently replaces a weapon");
assert.deepEqual([...storage], beforePreviewStorage, "previewing does not save an unintended loadout");
const previewed = choices.find(button => button.dataset.weaponChoice === "rocket_launcher");
const equipped = choices.find(button => button.dataset.weaponChoice === "railgun");
assert.equal(previewed.attributes.get("aria-pressed"), "true", "pressed state identifies the current preview");
assert.equal(previewed.label.hidden, true, "an unequipped preview is not labeled equipped");
assert.equal(equipped.attributes.get("aria-pressed"), "false", "equipped weapons do not masquerade as the selected preview");
assert.equal(equipped.label.hidden, false, "equipped labels remain visible while browsing other weapons");
nodes.get("[data-weapon-search]").value = "long range";
game.filterWeaponPicker();
assert.equal(equipped.hidden, false, "search finds weapons by their plain-language role");
assert.equal(game.activeLoadoutSlot, 0, "search keeps the selected slot");
click({ weaponFilter: data.WEAPON_GROUPS[1].id });
assert.equal(nodes.get("[data-weapon-search]").value, "", "choosing a category clears the previous search");
assert.equal(game.activeLoadoutSlot, 0, "category changes keep the selected slot");
assert.equal(game.previewWeaponId, "rocket_launcher", "category changes preserve the preview until another weapon is chosen");
assert.deepEqual(game.settings.loadout, beforePreview, "search and filters do not commit the preview");
click({ loadoutEquip: "" });
assert.equal(game.settings.loadout[0], "rocket_launcher", "the equip action commits the previewed weapon");
assert.equal(previewed.label.hidden, false, "equipping updates the weapon's equipped label");
assert.equal(equipped.label.hidden, true, "replacing a weapon clears its equipped label");
assert.equal(game.activeLoadoutSlot, 0, "equipping leaves the active slot selected");
assert.equal(game.focusedSlot, 0, "equipping restores keyboard focus to the enabled slot button");
assert.deepEqual(data.loadSettings().loadout, game.settings.loadout, "equipping persists the loadout");
game.settings.loadout = [...beforePreview];

game.activeLoadoutSlot = 0;
game.equipLoadoutSlot("blaster");
assert.deepEqual(game.settings.loadout, ["blaster", "railgun", "shotgun", "mine", "needle_launcher"], "equipped weapons swap without duplicates");
game.activeLoadoutSlot = 3;
game.equipLoadoutSlot("hammer");
assert.equal(game.settings.loadout[3], "hammer", "full loadout can replace a slot directly");
game.removeLoadout(1);
assert.equal(game.settings.loadout.length, 4);
assert.equal(game.activeLoadoutSlot, 4, "removal targets the newly empty slot");
game.activeLoadoutSlot = 4;
game.equipLoadoutSlot("mine");
assert.equal(game.settings.loadout.length, 5, "removed slots can be filled again");
game.removeLoadout(4);
game.equipLoadoutSlot(game.settings.loadout[0]);
assert.equal(game.settings.loadout.length, 4, "moving an already equipped weapon to the empty tail preserves the incomplete loadout");
assert.equal(game.activeLoadoutSlot, 3, "the selected slot follows the weapon after local empty-slot compaction");
assert.equal(game.settings.loadout[game.activeLoadoutSlot], game.previewWeaponId, "the active slot and preview refer to the same weapon after compaction");
game.activeLoadoutSlot = 4;
game.equipLoadoutSlot("mine");
game.activeLoadoutSlot = 2;
game.moveLoadout(2, -1);
assert.equal(game.activeLoadoutSlot, 1, "active controls follow reordering");
game.loadPreset(0);
assert.deepEqual(game.settings.loadout, game.settings.loadoutPresets[0].weaponIds);
assert.match(game.presetOptionsMarkup(), /value="0" selected/);
assert.deepEqual(data.loadSettings().loadoutPresets[0].weaponIds, beforePreview, "saved sets retain their exact order after editing");

game.settings.defaultLoadoutPreset = null;
const custom = [...game.settings.loadout];
game.renderSetup("quick");
game.renderSetup("quick");
assert.deepEqual(game.settings.loadout, custom, "returning to Quick Play keeps the current custom loadout");
game.settings.defaultLoadoutPreset = 0;
game.settings.loadout = [...data.DEFAULT_LOADOUT];
game.renderSetup("quick");
assert.deepEqual(game.settings.loadout, beforePreview, "a chosen saved default still applies on entry");
click({ loadoutRecommended: "" });
assert.deepEqual(game.settings.loadout, data.RECOMMENDED_LOADOUT, "the recommended action equips a complete beginner kit");
assert.deepEqual(data.loadSettings().loadout, data.RECOMMENDED_LOADOUT, "the recommended kit persists locally");
const presetManager = { innerHTML: '<input value="Unfinished name">' }, presetSelect = { innerHTML: "Current selection" };
nodes.set("[data-loadout-presets]", presetManager);
nodes.set("[data-preset-select]", presetSelect);
game.settings.loadout = [...game.settings.loadoutPresets[0].weaponIds];
game.updateLoadoutUi("", false);
assert.equal(presetManager.innerHTML, '<input value="Unfinished name">', "passive updates preserve unfinished preset names");
assert.equal(presetSelect.innerHTML, "Current selection", "passive updates preserve the preset dropdown");
assert.equal(presetSelect.value, "0", "passive updates select the matching preset without replacing its options");
assert.ok(saveButtons.every(button => button.disabled === false), "passive updates enable Save for a complete kit");
game.settings.loadout = game.settings.loadout.slice(0, 4);
game.updateLoadoutUi("", false);
assert.equal(presetSelect.value, "", "changing a preset kit switches the retained dropdown to Custom");
assert.ok(saveButtons.every(button => button.disabled === true), "passive updates still disable Save for incomplete kits");
game.settings.loadout = [...game.settings.loadoutPresets[0].weaponIds];
game.updateLoadoutUi("", false);
assert.equal(presetSelect.value, "0", "restoring the preset kit selects it again without replacing options");
assert.equal(presetManager.innerHTML, '<input value="Unfinished name">', "synchronizing preset selection preserves unfinished names");
game.settings.loadout = [...data.RECOMMENDED_LOADOUT];
game.updateLoadoutUi();
assert.match(presetManager.innerHTML, /data-preset-name/, "explicit changes refresh preset management");
nodes.delete("[data-loadout-presets]");
nodes.delete("[data-preset-select]");
game.mode = "training";

game.botDifficulty = "veteran";
game.timeLimitMinutes = 5;
game.settings.botCount = 12;
game.settings.matchSettings.training.botsStandStill = true;
assert.ok(game.matchSummary().includes(formatText(TEXT.setup.matchSummary, { bots: 12, difficulty: TEXT.setup.difficulties.veteran, minutes: 5 })));
assert.ok(game.matchSummary().includes(`${TEXT.trainingControls.botsStandStill}: ${TEXT.trainingControls.on}`));
const settingsSummary = {}, launchSummary = {};
nodes.set("[data-match-summary]", settingsSummary);
nodes.set("[data-launch-summary]", launchSummary);
for (const [selector, value] of [["#display-name", "Tester"], ["#map-seed", "TEST"], ["#bot-difficulty", "rookie"], ["#bot-count", "4"], ["#time-limit", "7"]]) nodes.set(selector, { value });
game.captureSetupPreferences();
assert.equal(settingsSummary.textContent, game.matchSummary());
assert.equal(launchSummary.textContent, game.matchSummary(), "match preferences update the summary beside Start");
const beforeTrainingToggle = launchSummary.textContent;
click({ trainingToggle: "botsStandStill" });
assert.notEqual(launchSummary.textContent, beforeTrainingToggle);
assert.equal(launchSummary.textContent, settingsSummary.textContent, "training toggles keep both match summaries synchronized");

let sent = 0;
game.mode = "global";
game.state = "lobby";
game.globalMultiplayer = { slots: ["railgun", null, "blaster", null, null], sendSlots: () => { sent++; } };
game.activeLoadoutSlot = 1;
game.previewLoadoutWeapon("railgun");
assert.equal(sent, 0, "previewing in a waiting room sends no lobby changes");
assert.deepEqual(game.globalMultiplayer.slots, ["railgun", null, "blaster", null, null]);
game.equipLoadoutSlot("railgun");
assert.deepEqual(game.globalMultiplayer.slots, [null, "railgun", "blaster", null, null], "global swaps preserve random slots");
assert.equal(sent, 1);
game.loadPreset(0);
assert.deepEqual(game.globalMultiplayer.slots, game.settings.loadoutPresets[0].weaponIds, "presets apply to global waiting rooms");
assert.equal(sent, 2);
game.settings.loadout = ["hammer"];
game.savePreset(1);
assert.deepEqual(game.settings.loadoutPresets[1].weaponIds, game.globalMultiplayer.slots, "global preset saves use the actual room loadout");
assert.match(game.loadoutEditorMarkup(true), /data-global-slots/);
game.applyRecommendedLoadout();
assert.deepEqual(game.globalMultiplayer.slots, data.RECOMMENDED_LOADOUT, "the recommended kit applies to the actual waiting-room slots");
assert.equal(sent, 3, "equipping the recommended kit sends one waiting-room update");
console.log("Armory previews, explicit equip, replacement/swaps, removal/reorder, recommended kit, saved defaults, Quick Play stability, training summary and global random slots passed.");

// Render multiplayer setup with a local service stub; no live room is created.
const globalSource = readFileSync(new URL("../src/globalMultiplayer.js", import.meta.url), "utf8").replace(/^import .*;\r?\n/gm, "").replace("export class", "class");
const Global = new Function("TEXT", "formatText", "WEAPONS", `${globalSource}\nreturn GlobalMultiplayer;`)(TEXT, formatText, data.WEAPONS);
const roomNodes = new Map();
const roomUi = { innerHTML: "", querySelector: selector => {
  if (selector === "[data-global-waiting]") return null;
  if (!roomNodes.has(selector)) roomNodes.set(selector, {});
  return roomNodes.get(selector);
}, querySelectorAll: () => [] };
const room = new Global(game, roomUi, () => "");
game.globalMultiplayer = room;
game.bindUi = () => {};
game.setMatchLoading = () => {};
game.sound = { setPaused() {}, setMusicScene() {}, startMusic() {} };
game.multiplayer = { playerId: "local", connected: true };
room.renderCreate();
assert.match(roomUi.innerHTML, /id="global-name"[\s\S]*?<details class="setup-options">[\s\S]*?id="global-bots"/, "global room identity stays visible while advanced settings collapse");
room.updateSlots = () => {};
room.renderRoom({ type: "welcome", roomName: "Test room", hostId: "local", phase: "lobby", humanCapacity: 4, configuredBotCount: 2, difficulty: "normal", timeLimitMinutes: 3, players: [{ id: "local", name: "Tester", pendingLoadout: ["railgun", null, null, null, null] }] });
assert.match(roomUi.innerHTML, new RegExp(TEXT.globalLobby.weapons));
assert.doesNotMatch(roomUi.innerHTML, /data-weapon-picker hidden/);
assert.match(roomUi.innerHTML, new RegExp(TEXT.globalLobby.emptySlot));
assert.equal(game.activeLoadoutSlot, 0, "waiting rooms open with the first armory slot selected");
assert.match(roomUi.innerHTML, /data-preset-select/);
assert.equal(roomNodes.get("[data-global-rules]").textContent, formatText(TEXT.setup.matchSummary, { bots: 2, difficulty: TEXT.setup.difficulties.normal, minutes: 3 }));
console.log("Global creation and waiting-room rendering preserve collapsed settings, the visible armory, presets and optional random slots.");
